import RPi.GPIO as GPIO
GPIO.setwarnings(False)
GPIO.setmode(GPIO.BCM)
GPIO.setup(2,GPIO.OUT)
GPIO.setup(3,GPIO.OUT)
GPIO.setup(4,GPIO.OUT)
GPIO.setup(17,GPIO.OUT)
GPIO.setup(27,GPIO.OUT)
GPIO.setup(22,GPIO.OUT)
GPIO.setup(5, GPIO.IN, pull_up_down=GPIO.PUD_UP)

GPIO.output(2,1)
GPIO.output(3,1)
GPIO.output(4,1)
GPIO.output(17,1)
GPIO.output(27,1)
GPIO.output(22,1)
import time
while (GPIO.input(5) ==True) :
        GPIO.output(2,0)
        time.sleep(1)
        GPIO.output(2,1)
	GPIO.output(3,0)
        time.sleep(1)
        GPIO.output(3,1)
        GPIO.output(4,0)
        time.sleep(1)
        GPIO.output(4,1)
        GPIO.output(17,0)
	time.sleep(1)
        GPIO.output(17,1)
        GPIO.output(27,0)
        time.sleep(1)
        GPIO.output(27,1)
        GPIO.output(22,0)
        time.sleep(1)
        GPIO.output(22,1)
